### ISSUE TITLE
Highlight Annotation

### ISSUE THREAD

**Issue by ajile-in** [PatriotExcalibur/PDFsharper#48]
Just cross-referencing [this issue](https://github.com/empira/PDFsharp/issues/16) from empira repo.
Is anyone aware of the Keys to be used. It would be of great help if you know and point me to some solution.

**Comment by mcnallys** [comment]
Are you adding the annotation to the page's annotation array?

Your best bet would be to make one in adobe and save the resulting document and then examine it in a tool called "iText Rups".  The adobe pdf reference document is a great place to look as well.

**Comment by ajile-in** [comment]
Yes, I am adding it to the Annotations array.
I will give a try to iText Rups. Thanks Scott.

**Comment by ajile-in** [comment]
@mcnallys I was able to successfully create `PdfHighlightAnnotation`. The use of iText Rups really helped.

**Comment by mcnallys** [comment]
Glad to hear it! Feel free to submit a PR and we'll get that ability added in.

**Comment by ajile-in** [comment]
Sure. I will submit a PR soon.

**Comment by mcnallys** [comment]
Closing issue due to lack of feedback.
